Update as suggested

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -67,8 +67,8 @@ jobs:
         run: npm ci
       - name: Run tests
         run: npm run test
-  generate-docs:
-    name: Generate docs
+  check-docs:
+    name: Check docs
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -83,4 +83,4 @@ jobs:
         run: npm run doc
       - name: Check generated docs
         run: |
-          test -z "$(git status --porcelain)" || exit 1
+          test -z "$(git status --porcelain)" || echo "::error title=Documentation is outdated::You need to run 'run npm doc'";exit 1;
